### PR TITLE
fix: Web Share Target text field merge

### PR DESCRIPTION
**Pull request by horvbalint**
Attempts to fix the issue: #1565 

As a solution we no longer merge every text type data shared with us into a single field inside the fetch request. Because this (sometimes) caused data loss. Now the three data types (title, text, url) are collected separately and then concatenated together in new lines before inserting them inside the text-area.

### CODE REVIEW

**Comment by horvbalint** [comment]
@TheWebTech can you please try this out and see If it solves the problem on your phone?

**Comment by userquin** [comment]
LGTM

Screenshot_20230202_190803_Chrome

**Comment by userquin** [comment]
@horvbalint do we need to sanitize html? Maybe my last commit should be reverted, it may be wrong if we don't check if there is html

**Comment by TheWebTech** [comment]
huh... odd. On desktop used the deploy preview installed it, then tried to share to it. The URL did not come through.

Used the mobile preview, and it worked just fine when installed by clicking the install prompt that the app itself pops up. It does not work if the user installs via the browser's UI.

I believe the issue with the method of install applies to both desktop and mobile. It's odd. Anyways that's separate from this issue.

Seems like you've got it working.

**Comment by horvbalint** [comment]
@userquin @TheWebTech I think with this last commit this is ready to be reviewed, so I will remove the draft flag. 
Texts that are shared are now treated as text when added to the editor and not as html, so no tag will be rendered inside the editor. I also add the text to the editor line-by-line so the bug of the lines collapsing on edit should be fixed as well.

**Review by TheWebTech — APPROVED** [review]
LGTM woo!

**Review by userquin — APPROVED** [review]

**Pull request merged**
