### PR TITLE
fix: Custom-emoji size on editor

### PR DESCRIPTION
**Pull request by ronilaukkarinen**
A visual representation of the issue:

image

After this change:

image

To think about in the future: There's an incosistency here, because in the post the emoji is wrapped with a class custom-emoji whereas in the editor the custom-emoji class is directly in the img.

### CODE REVIEW

**Comment by userquin** [comment]
@ronilaukkarinen can you read `CI errors` on contributing guide  :sweat_smile: ? Check `Semantic Pull Requests` entry: https://github.com/elk-zone/elk/blob/main/CONTRIBUTING.md#ci-errors

https://www.conventionalcommits.org/en/v1.0.0/#summary

**Comment by ronilaukkarinen** [comment]
> @ronilaukkarinen can you read `CI errors` on contributing guide sweat_smile ? Check `Semantic Pull Requests` entry: https://github.com/elk-zone/elk/blob/main/CONTRIBUTING.md#ci-errors
> 
> https://www.conventionalcommits.org/en/v1.0.0/#summary

Sure. I was thinking that for this small change I wouldn't have to clone and setup dev environment on my current new-ish Linux machine but what the heck let's do it. (You'll probably see more contributions after this :wink:)

I'll tackle the checks asap.

**Comment by userquin** [comment]
it is just PR title: I only use `perf: `, `fix: `, `feat: ` and `chore: `  with context variants: `perf(i18n): `, `fix(a11y): `, `feat(pwa): ` and `chore(i18n): `

**Comment by ronilaukkarinen** [comment]
> it is just PR title: I only use `perf: `, `fix: `, `feat: ` and `chore: ` with context variants: `perf(i18n): `, `fix(a11y): `, `feat(pwa): ` and `chore(i18n): `

Yeah just completed reading all the docs and figured that out myself right after :sweat_smile: :man_facepalming: 
Anyway all good now.

**Pull request merged**
