### PR TITLE
feat: use animate like icon

### PR DESCRIPTION
**Pull request by Innei**
https://user-images.githubusercontent.com/41265413/212352598-a80cee8f-39db-4eed-841b-666df18613d6.mov

### CODE REVIEW

**Comment by sxzz** [comment]
I think it's too similar with Twitter...

**Comment by Innei** [comment]
But now UI looks like Twitter too, right?

**Comment by edimitchel** [comment]
I see some improvement gap there
heart

**Comment by edimitchel** [comment]
About @sxzz feedback, why not using a different style: for example, doing a double beating with a solid wave leaving the heart in the background?

**Comment by boehs** [comment]
The icon should not be solid when unliked

**Pull request closed without merging**
