### PR TITLE
chore: upgrade to nuxt v3.2.0

### PR DESCRIPTION
**Pull request by danielroe**

### CODE REVIEW

**Comment by danielroe** [comment]
@sxzz Do you know the cause of the type issue?

**Comment by sxzz** [comment]
@danielroe I have no idea with this one. It could be a breaking change with Nuxt 3.2.

/cc @antfu

**Comment by danielroe** [comment]
I can confirm the issue is caused by the upgrade from Vue 3.2.45 to 3.2.47. When reverted there are no type errors.

**Pull request merged**
