### PR TITLE
feat: update info dialog

### PR DESCRIPTION
**Pull request by patak-dev**
Add @userquin and @shuuji3 to the info screen, and improve the text to be more aligned with the current state of the project (trying to encourage more contributions, remove the word Preview)

image

The Elk profile has also been updated

image

### CODE REVIEW

**Comment by userquin** [comment]
@patak-dev download gh avatars and add them to the corresponding folder

**Comment by patak-dev** [comment]
@userquin I run the `update:team:avatars` script 👍🏼

**Comment by userquin** [comment]
Check mobile, I guess we should center the avatars...

**Comment by userquin** [comment]
Sponsor links still pointing to our gh sponsor accounts: check https://deploy-preview-2741--elk-zone.netlify.app/settings/about (meet the team links):

imagen

**Comment by patak-dev** [comment]
@userquin both things are fixed. I ended up adding a `link` that each of us can point where they want. I pointed them to the mastodon accounts as I think it may work better here.

**Comment by userquin** [comment]
That's werid, when clicking new `link` in the meat the team links, back to the page, the page scrolls to the top.

**Comment by patak-dev** [comment]
> That's weird, when clicking new `link` in the meat the team links, back to the page, the page scrolls to the top.

weird, I think we could fix that later on if we find a way to do it

**Comment by userquin** [comment]
Maybe the problem is that links are local? https://github.com/elk-zone/elk/pull/2741/files#diff-008471c5036e53ede44053c408b5a9419e62e9d4e6e25cfc8141efdbd67ef45aR38

**Comment by userquin** [comment]
:eyes: `const vAutoFocus = (el: HTMLElement) => el.focus()`

**Comment by userquin** [comment]
feel free to merge the PR, we can fix the problem later

**Review by shuuji3 — APPROVED** [review]
Thank you! The new wording looks good too.

**Pull request merged**
