### PR TITLE
docs: fix elk screenshot on mobile

### PR DESCRIPTION
**Pull request by userquin**
Current:

elk-fixed-height-screenshot

Fix:

elk-fixed-width-screenshot

### CODE REVIEW

**Comment by sxzz** [comment]
image

but it'll be stretched on desktop devices

**Comment by userquin** [comment]
we should create a new one square

**Comment by danielroe** [comment]
What if you set both height and width?

**Comment by userquin** [comment]
upps, I'll try it, thx Daniel

**Pull request merged**
