### PR TITLE
feat(i18n): support for Russian locale (Russian Federation variant)

### PR DESCRIPTION
**Pull request by Bytedefined**
Full support for Russian locale (Russian Federation variant).

### Additional context

N/A

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [X] Translations update
- [ ] Other

### CODE REVIEW

**Comment by danielroe** [comment]
Is there any reason you have opened and closed this PR a couple of times?

**Comment by Bytedefined** [comment]
> Is there any reason you have opened and closed this PR a couple of times?
> 
> Edit: ah, maybe the semantic pr title check?

Yes, that, and also made some improvements, but don't know how to edit an already-made PR...

**Comment by danielroe** [comment]
Okay, no problem 😊 Don't worry, if you make any changes in your fork's branch they are automatically included in the PR.

Oh, and thanks for the PR!

**Comment by Bytedefined** [comment]
> Okay, no problem 😊 Don't worry, if you make any changes in your fork's branch they are automatically included in the PR.
> 
> Oh, and thanks for the PR!

Ah, okay. That's good to know.

And no problem!

**Comment by patak-dev** [comment]
We'll wait until we have a review, I'm discussing with someone to check the translations. Thanks for being patient here.

**Review by skryukov — COMMENTED** [review]
I think I never saw a `ru-RF` code before, it's always `ru-RU`. 🤔 I think we should change that before merging the initial support.

cc @patak-dev

**Pull request merged**
