### PR TITLE
fix(ui): Profile avatar image motion setting #3044

### PR DESCRIPTION
**Pull request by AndrewCrescencio**

### CODE REVIEW

**Review by shuuji3 — APPROVED** [review]
Thanks for the contribution! I confirmed this change stopped gif animation by replacing static image like png when enabled prefers-reduced-motion setting.

**Comment by AndrewCrescencio** [comment]
nice, just commenting on this, I was a little scared, I don't know if at some point it could happen that the profile doesn't have a photo or a static photo

**Comment by shuuji3** [comment]
Good point.

Mastodon has ensured `avatar_static` (https://docs.joinmastodon.org/entities/Account/#avatar) exists since v1.1.2 (in 2017), so I think we don't have to worry about that case, at least for Mastodon.

But the same property might not exist on other fediverse servers so it's safer to fall back to `avatar` property when there is no `avatar_static`. It's not optimal, but I think it's better than an empty image.

**Comment by shuuji3** [comment]
For example, something like this?
```diff
 const preferredMotion = usePreferredReducedMotion()
 const accountAvatarSrc = computed(() => {
-  return preferredMotion.value === 'reduce' ? account.avatarStatic : account.avatar
+  return preferredMotion.value === 'reduce' ? (account?.avatarStatic ?? account.avatar) : account.avatar
```

**Comment by shuuji3** [comment]
ref. GoToSocial returns static avatar like Mastodon: Routes and Methods - GoToSocial Documentation - https://docs.gotosocial.org/en/latest/api/swagger/

**Pull request merged**
