### PR TITLE
feat(editor): Respect default privacy setting of the account

### LINKED ISSUE #1040: Default post privacy setting
### Clear and concise description of the problem

People uses "unlisted/followers" as default posting privacy. But Elk always set posting privacy setting as "public" by default and there is no setting or fetching web settings from server

### Suggested solution

Best solution: Fetch the web setting from home server. and use it as default posting privacy

### Alternative

Second solution: Add a setting to set a default posting privacy for Elk

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by peterbud**
This PR changes default privacy setting of a post by considering the account's preferenced privacy setting when starting composing a post.

Also fixed an existing issue that empty drafts were not always cleared.

Fixes #1040 #1199

### CODE REVIEW

**Review by LittleSound — APPROVED** [review]

**Comment by userquin** [comment]
@peterbud can you send 2 separated PR, this will be reverted, see #1730

**Comment by peterbud** [comment]
@userquin sorry for the inconvenience.

However I'd need some help. The problem is that with the currant main branch the 'home' draft never gets cleared. Ever. See also #1199 . That means you will always have an 'elk-drafts' forever with the last privacy settings, and therefore the result of `getDefaultDraft` is never applied to a new post/toot.

The `clearEmptyDrafts` is called only at the unMounted hook of the `PublishFullWidget` but even that won't be called, as that compnent is never unmounted as I see, my guees is becaues `keepAlive:true`

I mistakenly tought the it's good to call `clearEmptyDrafts` once the post is empty, however it seems that a single `@` is also consiedered as empty, so that is not working as we see.

So where I'd need some advice: what is the best place / lifecycle hook to call `clearEmptyDrafts` to get rid of the empty drafts therefore preventing them danging there forever?

**Comment by userquin** [comment]
> The `clearEmptyDrafts` is called only at the unMounted hook of the `PublishFullWidget` but even that won't be called, as that compnent is never unmounted as I see, my guees is becaues `keepAlive:true`

You should also add that logic with `onDeactivate`.

> So where I'd need some advice: what is the best place / lifecycle hook to call clearEmptyDrafts to get rid of the empty drafts therefore preventing them danging there forever?

Use the same logic in this PR, just check if it has only 1 character that is `@` and you're done: change `isEmptyLogic`

**Comment by peterbud** [comment]
OK, I'll send a new PR. Many thanks!

**Pull request merged**
