### PR TITLE
feat: initial support for lists

### PR DESCRIPTION
**Pull request by boehs**
#372

### CODE REVIEW

**Comment by boehs** [comment]
@patak-dev I'd call this "ready for review". I've done testing and everything seems to be working, but future pull requests will include the ability to view the users in the list, edit the list, etc

**Comment by boehs** [comment]
Example here https://deploy-preview-1474--elk-zone.netlify.app/universeodon.com/list/2768

**Review by patak-dev — APPROVED** [review]
Nice, I think we can merge and iterate. We are probably not going to release for a few days so we could add this slowly to main.elk.zone without doing much buzz

**Comment by patak-dev** [comment]
Would you resolve the conflicts @boehs? Then let's merge :)

**Comment by boehs** [comment]
oops, that merge went terribly. One second

**Comment by boehs** [comment]
should be good once checks pass

**Comment by patak-dev** [comment]
Awesome, thanks! A solid first step 🙌🏼

**Pull request merged**
