### PR TITLE
fix: make attachement removal button static & more visible #1067

### LINKED ISSUE #1067: Cross for clossing images is almost invisible in white images
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [X] I am willing to provide a PR.

### Describe the bug

When adding images to a new publication a cross appears when hovering over the image, but this cross is almost invisible in white images.

### Reproduction video or screenshot

Screenshot 2023-01-13 at 12-13-23 Elk
The cross is almost invisible in this white background screenshot
elk-screenshot
Hovering over the cross

### Additional Context

The cross should be visible no matter the colour of the image.

### PR DESCRIPTION
**Pull request by dilinger**
The black background makes it a lot more obvious, and let's always leave it there rather than requiring a mouseover. Added the translated text as an aria-label for screenreaders/a11y, because "X" isn't super descriptive.

### Description

This takes a chainsaw to the existing image deletion button in the PublishAttachement component, but.. It's currently really hard to find/see, as described in #1067 and #1283.  It also makes it stylishly consistent w/ the Edit button.

This fixes #1067. Tested on both my laptop (firefox 102) and my phone (android 11).

### Additional context

---

### What is the purpose of this pull request? 

- [X] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Translations update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/elk-zone/elk/blob/main/CONTRIBUTING.md).
- [ ] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ ] Provide related snapshots or videos.
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).

### CODE REVIEW

**Comment by dilinger** [comment]
Oh yeah, here's what it looks like on firefox:

Screenshot-2023-01-18,04-24-09

**Comment by antfu** [comment]
Can we keep using the icon instead of the char `X`? And also would be better to make the button square

**Review by edimitchel — CHANGES_REQUESTED** [review]
Please make it round

Capture d’écran 2023-01-18 à 16 42 57

Capture d’écran 2023-01-18 à 16 46 51


Use also [i-ri:close-line icon](https://icones.js.org/collection/ri?s=close-line)

**Comment by dilinger** [comment]
Um, square or round? I personally like it square so that it matches both the image itself as well as the Edit button.

**Comment by Servelan** [comment]
Can't see the image delete icon (using the web version). This is an accessibility issue, btw.

**Comment by edimitchel** [comment]
We should probably use an invert filter to be sure the contrast is respected.

**Comment by dilinger** [comment]
Alright, how's this? Here's what it looks like on my end:

Screenshot-2023-01-21,03-05-32

**Review by patak-dev — APPROVED** [review]
Thanks! Let's merge it and keep iterating. We'll need to extract a close button component that we can reuse in other places in the app later.

**Comment by Servelan** [comment]
Accessibility would suggest a bigger x (50% bigger).  Good background, 
good contrast, however.

**Comment by patak-dev** [comment]
@Servelan PR or issue welcome about the 50% bigger, thanks for your feedback

**Pull request merged**
