### PR TITLE
chore: upstream fixed a issue in `useHead`

### PR DESCRIPTION
**Pull request by LittleSound**
`unhead` fixes an issue in `useHead` (PR: https://github.com/unjs/unhead/pull/96). I wrote a function for Elk as a temporary solution (PR: #199) before fixing this problem upstream. Now that it has been fixed, I will update the dependency to the repaired version in this PR and remove and modify the code from the previous temporary fix.

### CODE REVIEW

**Comment by userquin** [comment]
@LittleSound there is PR in progress #1782

**Review by antfu — APPROVED** [review]

**Comment by userquin** [comment]
@antfu changing only the workaround will not work, check my PR, we also need to fix the problem having `keepAlive`, since there is a lot of title changes when you traverse the app: for example, navigate ntofications tabs, go to your account and navigate followers, following, back to posts and navigate tabs... the title will have a race condition

**Comment by LittleSound** [comment]
Thanks for trying to fix this, I'll take some time to look at #1776 and #1782 you said to see what the problems are so far.

**Comment by userquin** [comment]
https://streamable.com/e1jmkr

**Comment by LittleSound** [comment]
@userquin 

> changing only the workaround will not work, check my PR, we also need to fix the problem having keepAlive, since there is a lot of title changes when you traverse the app: for example, navigate ntofications tabs, go to your account and navigate followers, following, back to posts and navigate tabs... the title will have a race condition.

I just updated nuxt to 3.2.2 and used the useHead function to fix the issue raised in 1776, if there are other issues with the useHead function, can you provide a specific way to reproduce them?

> EDIT: `i18n::setLocale` is async, we need to await on the client plugin to avoid flickering (when user `lang !== 'en-US'`) on F5

I think i18n should have the same behavior on server and client, and it should not be asynchronous and causing flickering. Server should be able to read the user's current language in the cookie and return the correct content, at least it works this way in the project I'm working on.

**Comment by userquin** [comment]
@LittleSound

Just switch to another locale (`!== 'en-US'`) and refresh page, you will see the title and nav bar flickering (en-US then user lang).

About i18n on server, we can enable cookie, but the problem is the hydration, if i18n restores properly user locale I guess we don't need the `useHydratedHead` hack.

**Comment by LittleSound** [comment]
@userquin 
Maybe the flickering problem caused by i18n should be a different issue from issue #1776

> About i18n on server, we can enable cookie, but the problem is the hydration, if i18n restores properly user locale I guess we don't need the useHydratedHead hack.

Maybe we can try to solve the problem in this direction, it looks simpler instead of adding `isHydrated` in many places, adding these logic branches obviously increases the developer's mental burden and code complexity.

**Comment by userquin** [comment]
> @userquin Maybe the flickering problem caused by i18n should be a different issue from issue #1776
> 

:thumbsup: 

> Maybe we can try to solve the problem in this direction, it looks simpler instead of adding `isHydrated` in many places, adding these logic branches obviously increases the developer's mental burden and code complexity.

The same complexity we have rn: replace `useHeadFixed`  with `useHydratedHead`... ;)

**Pull request closed without merging**
