### PR TITLE
feat(i18n): add Catalan locales

### PR DESCRIPTION
**Pull request by rbnval**

### CODE REVIEW

**Comment by userquin** [comment]
@rbnval can you remove your another PR and include here changes in [config/i18n.ts](https://github.com/elk-zone/elk/pull/1576/files#diff-fb2fd6012fe1954c1021496a3bc2260acb3878612e64f1e0dbdbf30862bbf8f8)

**Comment by userquin** [comment]
@rbnval `es-CA-valencia` is supported by browsers?

**Comment by userquin** [comment]
There are a lot of duplicates entries, you don't need to override entries if not changed in `es-CA-valencia.json` file

**Comment by carlesbarreda** [comment]
Hi @rbnval,
@userquin [said me](https://github.com/elk-zone/elk/pull/1634#issuecomment-1417470281) that you started this PR and maybe I can review. I can't found how to setup GitHub Desktop or the link to [StackBlitz Codeflow](https://stackblitz.com/~/github.com/elk-zone/elk/pull/1577) for do the contribution, all the time I get errors or don't have permissions to push the commit. I copied your translations and extract with a script to add to PR #1634 while found a solution.

How you said, Edge and Firefox has support for valencià. Edge uses `ca-Es-VALENCIA` and Firefox `ca-valencia`, in [this maillist](https://www.alvestrand.no/pipermail/ietf-languages/2006-October/005131.html) comment that `ca-x-valencia` its possible too. You can check autodetection working in Edge and Firefox in the [preview build](https://deploy-preview-1634--elk-zone.netlify.app/), but I duplicated the json file.

For not duplicate the json file we can chosse, for example, `ca-valencia` as the locale name or, as workaround, split in two locales for valencià has autodetection in all browsers that has support.

**Comment by userquin** [comment]
Firefox seems to include both, Chrome seems to only have support for Galego and Catalá, missing Valencià and I haven't found a way to include a custom one:

imagen


This script seems to show plurals properly in Chrome/Edge and Firefox, but check if the output is ok:
```ts
[1, 12, 123, 1234, 12345, 123456, 1234567].forEach((n) => {
  const acc = {}

  Array.from(['ca-ES', 'ca-ES-valencia', 'ca-Es-VALENCIA', 'ca-x-valencia', 'ca-valencia']).forEach((l) => {
    const nf = new Intl.NumberFormat(l, {
      style: 'decimal',
      maximumFractionDigits: 0,
    })
    const nf2 = new Intl.NumberFormat(l, {
      notation: 'compact',
      compactDisplay: 'short',
      maximumFractionDigits: 1,
    })
    acc[l] = {
      number: n,
      format: nf.format(n),
      compact: nf2.format(n),
    }
  })
  console.table(acc)
})
```

**Comment by userquin** [comment]
I'll check if we can add some alias to avoid adding multiple entries only for Valencià...

**Comment by userquin** [comment]
@rbnval @carlesbarreda I'll open a branch for this and so you can work on it, what do you think?

**Comment by carlesbarreda** [comment]
Nice, I tried to contribute to this PR without luck, for this I continued updating the PR #1634

**Comment by userquin** [comment]
@rbnval @carlesbarreda s this PR ready?

**Comment by carlesbarreda** [comment]
Yes, is superseded by #1759

**Pull request closed without merging**
