### PR TITLE
feat(i18n): Update French translations

### PR DESCRIPTION
**Pull request by KaKi87**
- Added 1 missing key
- Edited 2 "cacher" -> "masquer" keys
- Fixed "répondre à" -> "réponse à" key

### CODE REVIEW

**Comment by KaKi87** [comment]
❓ @Shinigami92

**Comment by Shinigami92** [comment]
> question @Shinigami92

everything okay?
do you have a question?
I'm german and have zero knowledge in french so I cannot review this PR. I just did issue/PR triaging yesterday and updated the missing labels and so on.

However it now says that you need to rebase to resolve the conflict :slightly_smiling_face: 

You can ask on https://chat.elk.zone/ in the #i18n channel if someone could review the PR

**Review by AstroOrbis — APPROVED** [review]

**Comment by AstroOrbis** [comment]
Can confirm these are correct

**Review by suyundukov — APPROVED** [review]
LGTM.

**Review by antfu — APPROVED** [review]

**Comment by shuuji3** [comment]
The only task was swapping two lines. Thanks for your contribution! @KaKi87

**Pull request merged**
