### PR TITLE
feat(tiptap): add discord-style emoji suggestion support

### PR DESCRIPTION
**Pull request by ahonn**
CleanShot 2023-01-14 at 11 15 23

https://user-images.githubusercontent.com/9718515/212448271-3a7db7be-f369-4e52-8abd-7c274dc1ab00.mp4

### CODE REVIEW

**Comment by sxzz** [comment]
image

We suggest to provide a screenshot in PR.

**Comment by ahonn** [comment]
> image
> 
> We suggest to provide a screenshot in PR.

Done, and also added a video

**Comment by wakest** [comment]
oh awesome! I was just about to make a issue about this! glad there is already a pr!

**Comment by danielroe** [comment]
I'm currently getting double popups in Firefox on MacOS:

CleanShot 2023-01-16 at 01 05 35@2x

**Comment by ahonn** [comment]
> I do notice the flickering when typing

I don't quite understand what the flickering when typing means here (suggestion width change?), can you elaborate?

**Comment by antfu** [comment]
@danielroe it should be fixed by https://github.com/elk-zone/elk/pull/1123

**Pull request merged**
