### PR TITLE
feat: add Bluesky and Friendica icons

### PR DESCRIPTION
**Pull request by shuuji3**
This implements additional two icons (Bluesky and Friendica) for #2472

### CODE REVIEW

**Comment by patak-dev** [comment]
Something is odd, in the Netlify preview link the new icons aren't rendering
image

**Comment by shuuji3** [comment]
Sorry, I simply forgot to include `package.json` update when handling multiple branches 🙏🏻

**Comment by shuuji3** [comment]
You should be able to see the icons now. Maybe cache clear is needed.

Screenshot from 2024-01-18 17-40-11

**Review by patak-dev — APPROVED** [review]
awesome, thanks!

**Pull request merged**
