### PR TITLE
fix(a11y): allow pinch to zoom

### PR DESCRIPTION
**Pull request by userquin**
This PR is related to https://github.com/elk-zone/elk/pull/1501

/cc @ronilaukkarinen can you test pinch to zoom in this PR preview? Your fix not working on my Android device, there is some pan x/y in body styles that prevents it.

https://streamable.com/y6cnyy

### CODE REVIEW

**Comment by ronilaukkarinen** [comment]
> This PR is related to #1501
> 
> /cc @ronilaukkarinen can you test pinch to zoom in this PR preview? Your fix not working on my Android device, there is some pan x/y in body styles that prevents it.
> 
> https://streamable.com/y6cnyy

Maybe I missed something, I'll try it asap.

**Comment by ronilaukkarinen** [comment]
@userquin Fetched and pulled this PR, tested on a real device (OnePlus 8T with Google Pixel Android 13). 

It works: https://user-images.githubusercontent.com/1534150/215325700-cd23ea4c-2875-4469-8d97-ea4e83406593.mp4

Sorry for your trouble! I completely forgot `touch-action: pan-x pan-y;` from the commit...

**Comment by userquin** [comment]
> @userquin Fetched and pulled this PR, tested on a real device (OnePlus 8T with Google Pixel Android 13).
> 

Next time just test it using preview link above, you don't need to test in your local ;)

> It works: https://user-images.githubusercontent.com/1534150/215325700-cd23ea4c-2875-4469-8d97-ea4e83406593.mp4
> 
> Sorry for your trouble! I completely forgot `touch-action: pan-x pan-y;` from the commit...

no problem, I didin't test it in your PR :sweat_smile:

**Comment by ronilaukkarinen** [comment]
> > @userquin Fetched and pulled this PR, tested on a real device (OnePlus 8T with Google Pixel Android 13).
> 
> Next time just test it using preview link above, you don't need to test in your local ;) `Deploy Preview` link

:man_facepalming: Stupid me... so used to manual testing and often times running way too many projects at the same time so tend to overlook things. Elk has really fancy CI and deploy-previews I have not seen before, congrats for the well built workflow!

**Review by Shinigami92 — APPROVED** [review]
Works on iOS PWA

I discussed on Discord with @userquin that he implements an opt-out setting later in a separate PR,
so that user can decide if they want this behavior or not

e.g. Discord or Twitter does not behave like that in App-Mode

**Comment by ronilaukkarinen** [comment]
> I discussed on Discord with @userquin that he implements an opt-out setting later in a separate PR,
so that user can decide if they want this behavior or not

It's a good thing to give the users more options but I think it should not disabled by default as it's an accessibility feature unless it's clear that it can be enabled in the settings, this meaning that the Accessibility related settings should be in their own category in the Settings, for example under it would be the font-size and zoom settings, leaving only color and possibly other UI related future settings under the Interface settings.

> e.g. Discord or Twitter does not behave like that in App-Mode

That has been on of their biggest downsides and cannot be changed because of the big corporative decisions behind them. This is not by far the only thing wrong on those platforms accessibility-wise. But on the other note, they also have actual apps on mobile that usually don't have zoom enabled. Yet I loathe apon the idea. Instagram has zoom enabled on the feed view only on images, not on text, better than nothing I guess. Zoom should always be universally enabled and allowed by default. Many don't get that unless their eyesight goes bad.

**Comment by Shinigami92** [comment]
@ronilaukkarinen yes, yes, sure be default its on, that's why I said opt-out, not opt-in

**Comment by ronilaukkarinen** [comment]
> @ronilaukkarinen yes, yes, sure be default its on, that's why I said opt-out, not opt-in

My brain picked it out it the wrong way :smile:  Just wanted to underline the issue :+1: 
Keep up the good work!

**Comment by danielroe** [comment]
At the moment I can't seem to pinch-to-zoom into images/media, only into arbitrary app elements.

**Comment by userquin** [comment]
> At the moment I can't seem to pinch-to-zoom into images/media, only into arbitrary app elements.

This PR is about accesibility, allow pinch to zoom on mobile: check https://github.com/elk-zone/elk/pull/1501

**Comment by userquin** [comment]
@ronilaukkarinen @Shinigami92 PR for setting here https://github.com/elk-zone/elk/pull/1517

**Pull request merged**
