### PR TITLE
feat(i18n): Emojimart localization and `fetching` entry at `en` …

### PR DESCRIPTION
**Pull request by mrcego**
…and `es` bases, and `es-419` locale

I'm lack of knowledge about advanced ways to import dynamically modules/files from third party dependency, so I'm summoning @userquin for help (lol).

More info: https://github.com/missive/emoji-mart#-internationalization

Updated: added `tooltip.pick_an_icon` entry too.

### CODE REVIEW

**Comment by userquin** [comment]
maybe we change to this or split 2 last imports in separated entries:

imagen

**Comment by userquin** [comment]
@patak-dev maybe we can revert my last commit and resolve 3 dynamic imports in parallel: check screenshot on previous comment

**Review by patak-dev — APPROVED** [review]
I think we can move forward with this, thanks for working on it!
Later on, it would be cool if we could use placeholders to avoid delaying showing the picker, it took a bit of time the first time I press the emoji button.

**Comment by mrcego** [comment]
> I think we can move forward with this, thanks for working on it!
> Later on, it would be cool if we could use placeholders to avoid delaying showing the picker, it took a bit of time the first time I press the emoji button.

It should be showing a _fetching_ text instead. Maybe my mistake with translation?

**Comment by patak-dev** [comment]
Oh, maybe my bad, and it was already taking time to load at first because it is loaded lazily the first time, no?

**Comment by mrcego** [comment]
> Oh, maybe my bad, and it was already taking time to load at first because it is loaded lazily the first time, no?

I was able to reproduce it but setting 4G slow network. Interesting. Placeholder is shown but dissapears seconds later with emojis loading one by one.

**Comment by userquin** [comment]
> Oh, maybe my bad, and it was already taking time to load at first because it is loaded lazily the first time, no?

yes, we can keep json files with the promise, but the picker will also await to be resolved (twitter.json)

**Pull request merged**
