### PR TITLE
feat: keyboard status navigation with `j`/`k`

### PR DESCRIPTION
**Pull request by shuuji3**
resolves `j`/`k` navigation part of #1858

### CODE REVIEW

**Comment by shuuji3** [comment]
This implementation is working well if we disable the experimental virtual scrolling. When enabled and a post has a large height, the next post is not loaded until it is on-screen. As a result, this keyboard navigation code fails to find the next post to focus on and stack to the last post or is forced to go to the top post.

We are using `DynamicScroller` (https://github.com/Akryum/vue-virtual-scroller/blob/master/packages/vue-virtual-scroller/README.md#dynamicscroller) but it has little option to customize so I'm not sure how to fix this issue.

I'll disable this keyboard shortcut when the virtual scroller is enabled. But that means most users cannot use it as it is enabled by default.

**Comment by shuuji3** [comment]
Disabled this feature when "Virtual Scrolling" is enabled and add instructions to do so in the shortcut help dialog.

image

**Comment by patak-dev** [comment]
I'm not sure about adding j/k only when virtual scrolling is disabled. It may push users to disable it and we could get performance reports later on. Maybe we could wait to see if a way to have it always enabled comes up?

**Comment by shuuji3** [comment]
Right, that's not an ideal situation. OK, let's revert the message to encourage disabling virtual scrolling and seek a solution.

**Review by patak-dev — APPROVED** [review]

**Comment by shuuji3** [comment]
Thanks!

**Pull request merged**
