### PR TITLE
fix: handle undefined `._` property on `useUserLocalStorage`

### LINKED ISSUE #1056: "Sign Out" doesn't do anything
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [ ] I am willing to provide a PR.

### Describe the bug

If I do this:

- Click on my avatar at the bottom left
- Select "Sign out <account name>"

nothing happens. I would have expected to be signed out.

Same if I'm logged in with multiple accounts.

### Reproduction video or screenshot

image

### Additional Context

```
entry.dd4eda74.js:1 TypeError: Cannot read properties of undefined (reading 'forEach')
    at BS (entry.dd4eda74.js:12:58888)
    at vD (entry.dd4eda74.js:12:58294)
    at $n (entry.dd4eda74.js:1:13272)
    at Ot (entry.dd4eda74.js:1:13351)
    at Hv (entry.dd4eda74.js:1:15334)
    at m (DropdownItem.vue.899418ca.js:1:562)
    at $n (entry.dd4eda74.js:1:13272)
    at Ot (entry.dd4eda74.js:1:13351)
    at HTMLDivElement.n (entry.dd4eda74.js:1:67403)
```

### PR DESCRIPTION
**Pull request by tom-sherman**
Fixes #1056

I'm new to Vue, could someone explain to me waht the `._` property actually is? I can't find any docs on it.

I fear this PR just papers over the cracks of the bug and doesn't solve the root cause.

### CODE REVIEW

**Review by antfu — APPROVED** [review]

**Comment by antfu** [comment]
The `._` is an arbitrary property to store the map across multiple calls. It's nothing special.

**Comment by sxzz** [comment]
@antfu Oh I reverted `._` cache in https://github.com/elk-zone/elk/pull/1013#discussion_r1068360516

Could you please try to improve that? (I have no idea about it)

**Comment by tom-sherman** [comment]
Can we keep the track in a ref instead?

**Comment by tom-sherman** [comment]
@antfu @sxzz I created a new issue https://github.com/elk-zone/elk/issues/1068

**Pull request merged**
