### PR TITLE
feat(i18n): missing and rewording `es` and `es-419` keys

### PR DESCRIPTION
**Pull request by mrcego**
Changes:

- `es` locale
   - `account.copy_account_name`
   - `account.requested`
   - Some reword.

- `es-419` locale
   - `account.requested`
   - `confirm.block.confirm` missing colon
   - Some reword.

cc @userquin

### CODE REVIEW

**Review by userquin — APPROVED** [review]
Why vscode settings changed?

**Comment by mrcego** [comment]
> Why vscode settings changed?

Presumable from main branch? I can revert it anyway.

**Comment by userquin** [comment]
Just asking

**Comment by patak-dev** [comment]
I think no lang changes should be reverted

**Review by patak-dev — APPROVED** [review]

**Pull request merged**
