### PR TITLE
feat(i18n): Update Japanese localization

### PR DESCRIPTION
**Pull request by shuuji3**
### Description

Because of the recent active development, many texts lack Japanese translation now. This PR adds/updates these missing Japanese localization.

**Before**
Screenshot 2023-01-16 at 15 18 54

**After**
Screenshot 2023-01-16 at 17 39 00

### Additional context

Although there are small changes, the current Japanese localization is mostly done by the initial submission #228 (created on Nov 29, 2022).

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [x] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/elk-zone/elk/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ ] Provide related snapshots or videos.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).

### CODE REVIEW

**Comment by shuuji3** [comment]
Note: If there is someone who can review or propose better localization, feel free to review or put comments.

**Comment by shuuji3** [comment]
This PR is ready for review!

**Comment by shuuji3** [comment]
This PR is ready for review now!

**Review by kazupon — APPROVED** [review]
Thank you for four contribution!
This PR is perfect! 💯

**Comment by shuuji3** [comment]
Thank you so much for the quick reviewing! 😀

I'll continue updating strings when new ones are added. Can I request @kazupon-san to review a future PR too?

**Comment by kazupon** [comment]
@shuuji3 yeah! If you would send a new PR, you can assign or ping to me :)

**Comment by kazupon** [comment]
@shuuji3 yeah! If you would send a new PR, you can assign or ping to me :)

**Comment by shuuji3** [comment]
OK, thanks! @kazupon

**Pull request merged**
