### PR TITLE
feat(a11y): make menu buttons in 'More' dropdown selectable with the keyboard

### PR DESCRIPTION
**Pull request by jyn514**
previously, these were pure divs, without a `<button>` element, and could not be selected with `Tab`, rendering them keyboard-inaccessible.

see also https://github.com/elk-zone/elk/pull/2767 (cc @userquin). that uses a slightly different approach; it adds a disabled anchor instead of using buttons. i think this html is more semantically accurate, but i don't mind changing it if you so desire.

fixes https://github.com/elk-zone/elk/issues/2974

### CODE REVIEW

**Comment by jyn514** [comment]
> 8:31:15 PM: Failed during stage 'checking build content for changes': Canceled build due to no content change

i am not sure why this thinks nothing changed; i tested it locally with `pnpm dev` and it's definitely selectable now where it wasn't before.

**Comment by userquin** [comment]
can you update your main and merge changes in this PR?

**Comment by userquin** [comment]
> i am not sure why this thinks nothing changed; i tested it locally with `pnpm dev` and it's definitely selectable now where it wasn't before.

What do you mean? The buttons are there:

<details>
<summary><i>Buttons on StatusActionsMore</i></summary>

imagen
</details>

**Comment by userquin** [comment]
We should do the same also in `components/account/AccountMoreButton.vue`

**Comment by jyn514** [comment]
> can you update your main and merge changes in this PR?
> do the same also in `components/account/AccountMoreButton.vue`

done :)

> What do you mean? The buttons are there (also in the PR preview):

i mean the comment the github bot posted on this PR, that says the build was cancelled. maybe i'm misinterpreting it somehow, clearly the preview is showing up.

> add type="button" when is is button in components/common/dropdown/DropdownItem.vue: iirc type by default is submit

can you say more? i'm looking at the rendered button and i don't see any `submit` attribute. does it affect the event type or something like that?

i glanced at DropdownItem but i don't see anything related to `submit`; the closest is `:is="is"` in a component. maybe i'm missing something, i've never used react before :sweat_smile: 

image

**Comment by jyn514** [comment]
> i mean the comment the github bot posted on this PR, that says the build was cancelled. maybe i'm misinterpreting it somehow, clearly the preview is showing up.

ohhhh that's for the *docs*, not for the live preview of the site. that makes more sense.

**Comment by userquin** [comment]
`const type = computed(() => is === 'button' ? 'button' : null)`

Then add `:type="type"` below `:is="is"` in the template

**Comment by userquin** [comment]
We should use props destr. instead with defaults (enabled by default in vue 3.5)

**Comment by jyn514** [comment]
> it broke at first (apparently NuxtJS can't handle `null`?) so i just had it fallback to `submit`

oh wait apparently this started working again?? the only thing i changed was the order `:type` appears in the element ...

anyway, i've reverted this change, so now `type=""` only appears for button elements, not other dropdown items.T

**Comment by userquin** [comment]
Use undefined instesd null

**Review by shuuji3 — APPROVED** [review]
Sorry for taking a while to review 🙏🏻 This is a great accessibility improvement! Thank you so much.😀 

screenshot of context menu and accessibility tree view on devtool. it shows all menu items can be focusable and button elements

**Pull request merged**
