### PR TITLE
feat(i18n): add Catalá and Valencià translations

### PR DESCRIPTION
**Pull request by carlesbarreda**
I updated the config file and ca.json in my new branch and make new PR.
I hope this time I maked the correct steps for contributing.

### CODE REVIEW

**Comment by userquin** [comment]
have you checkout my branch from Elk and then create your PR from it?

**Comment by carlesbarreda** [comment]
@userquin :( 

> have you checkout my branch from Elk and then create your PR from it?

Yes, sorry I pulled to `main` branch not to userquin/feat-add-catala-and-valencia :(

**Comment by userquin** [comment]
changed

**Comment by carlesbarreda** [comment]
Thanks @userquin, it's my first time

**Comment by carlesbarreda** [comment]
@userquin I removed the duplicated strings and changed the [locale to `ca-valencia`](https://github.com/elk-zone/elk/pull/1577#issuecomment-1430537693).

**Comment by userquin** [comment]
@carlesbarreda @rbnval is this PR ready to be merged in my branch?

**Comment by carlesbarreda** [comment]
> @carlesbarreda @rbnval is this PR ready to be merged in my branch?

Yes, is up to date

**Comment by userquin** [comment]
@carlesbarreda why are you merging main? all changes shouldn't appear as new :thinking:

**Comment by carlesbarreda** [comment]
> @carlesbarreda why are you merging main? all changes shouldn't appear as new (55 files changed) 🤔

Sorry, I'm not a developer don't how works, it's my first contribution.
I merge main to get the locales files updated and then translate the new strings.

**Comment by userquin** [comment]
@carlesbarreda you should have pinged me to update my PR, I'll check what we can do...

**Comment by userquin** [comment]
ok, I'll discard any change made when merging this Pr into my PR (keeping only `ca**.json` files, I'll register them in another commit) :crossed_fingers: 

I'll merge later, finishing another PR preview.

**Comment by carlesbarreda** [comment]
> 

Last merge don't have new strings, I can revert the commit

> > @carlesbarreda why are you merging main? all changes shouldn't appear as new (55 files changed) 🤔
> 
> Sorry, I'm not a developer don't now how works, it's my first contribution. I merge main to get the locales files updated and then translate the new strings.

Last merge don't have new strings, I can revert the commit


> ok, I'll discard any change made when merging this PR into my PR (keeping only `ca**.json` files, I'll register them in another commit) 🤞
> 
> I'll merge later, finishing another PR preview.

Ok, I keep a backup of the files just in case.

**Comment by userquin** [comment]
Maybe it will be better to just send a new one from main, quite simple since you have only to include 2 json files and modify the i18n.ts module.

**Comment by carlesbarreda** [comment]
> Maybe it will be better to just send a new one from main, quite simple since you have only to include 2 json files and modify the i18n.ts module.
> 
> EDIT: on merge I'll suggest to include @rbnval as co-author.

Ok, I close this PR #1761 for don't get confused and open new PR from main branch

**Comment by userquin** [comment]
@carlesbarreda are you on discord? if you have any problem send me a DM in i18n > spanish channel

https://discord.gg/6n5Qtv4c

**Comment by carlesbarreda** [comment]
> @carlesbarreda are you on discord? if you have any problem send me a DM in i18n > spanish channel
> 
> https://discord.gg/6n5Qtv4c

The new PR #1823, close this.

(Sorry, I have had a visitor and I have been entertained)

**Pull request closed without merging**
