### PR TITLE
feat: finish list CRUD

### LINKED ISSUE #372: feat: user lists
Implement creating / showing lists on Elk.

The Mastodon web client has this feature:

Screenshot 2022-12-08 at 9 56 59 AM

### PR DESCRIPTION
**Pull request by boehs**
Implements

- [x] Create list
- [x] Delete list
- [x] Edit list name

~~Still does not fix that one terrible issue.~~

~~For creating and deleting lists, I'm triggering a full page reload which is terrible.~~ I tried for a bit to figure out a good way to update the pagination, and then I gave up.

#1483 closes #372 

oh, it also fixes the https://github.com/elk-zone/elk/issues/372#issuecomment-1408720858 in I think the best way, but other ideas welcome

new list view
editing list name
sizing fix

### CODE REVIEW

**Comment by boehs** [comment]
@patak-dev I think this is good for review

**Comment by userquin** [comment]
@boehs I'll try to remove the page reload also including some form and adding missing policy on creation

**Comment by boehs** [comment]
Thank you so much!

**Comment by boehs** [comment]
@userquin do I need to do something to merge these in?

**Comment by userquin** [comment]
@boehs yes please, merge main

**Comment by boehs** [comment]
done? if that's what you mean

**Comment by boehs** [comment]
oh wait to be clear I was talking about your changes, not this branch. I don't see them in the commit log

**Comment by userquin** [comment]
@boehs you should merge main from Elk into your main branch, the update list-CRUD branch, your main branch is 100+ commits behind

**Comment by boehs** [comment]
ooh

**Comment by boehs** [comment]
image
it looks fine on my screen

**Comment by userquin** [comment]
@boehs forgot it, browser cache...

**Comment by boehs** [comment]
I still don't see your changes. Are you still working on them or...

**Comment by userquin** [comment]
@boehs I'll push my changes, not yet ready to be merged, we need to move some logic

**Comment by userquin** [comment]
This PR is not yet ready, we need to apply some styles and fix `PWA Install Widget`.

**Comment by userquin** [comment]
I'll add error handling later...

**Comment by boehs** [comment]
> we need to fix max-width

Should be fixed

**Review by patak-dev — APPROVED** [review]
This is a huge step forward! Amazing work 🔥
Let's merge and try to release tomorrow

**Pull request merged**
