### PR TITLE
fix: Allow viewport zoom

### PR DESCRIPTION
**Pull request by neilstuartcraig**
Currently, users can't scale (pinch zoom) on Elk mobile devices, this means that it's difficult/impossible to read/see some images posted. This PR allows zooming, which is also an accessibility requirement, according to [Mozilla Developer Network docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag#viewport_basics):

> `maximum-scale`: ...Any value less than 3 fails accessibility...

> `user-scalable`: ...Setting the value to 0, which is the same as no, is against Web Content Accessibility Guidelines (WCAG)...

This PR changes the `viewport` meta element from:
```
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0,viewport-fit=cover">
```

to
```
<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=1,viewport-fit=cover">
```

(noting that `maximum-scale` has a default and maximum of `10` so this will be the maximum unless it's re-added with a specific value)

### CODE REVIEW

**Comment by cooperaj** [comment]
Mmm, unless I'm missing something this isn't doing anything in Android 13 Chrome?

**Comment by neilstuartcraig** [comment]
> Mmm, unless I'm missing something this isn't doing anything in Android 13 Chrome?
> 
> Using the deployment preview above

Oh, I didn't see the preview link (that's really cool!). 
I confirm it's not doing anything on Android 13 Firefox either. I'll have a look and get it sorted, thanks for the quick reply.

**Comment by neilstuartcraig** [comment]
This is now allowing pinch-zoom on the whole page but not on images. I'll keep going! I believe it'll be CSS again now that the viewport config is unlocked.

**Comment by peterbud** [comment]
See #668 and  #1367

**Comment by patak-dev** [comment]
Thanks for the PR @neilstuartcraig, but disabling zooming in the app is intentional (as other similar apps do). We need to add pinch to zoom for images (and where it makes sense in the future). There is work ongoing to support this as linked by @peterbud.

**Pull request closed without merging**
