### PR TITLE
chore(deps): Update masto.js

### LINKED ISSUE #2609: Elk completely stopped working on iOS 15
Elk does not work at all anymore on iOS 15 (15.8.1). It also does not work anymore when installed as PWA.

I am getting the below error anywhere.

TypeError: AbortSignal.timeout is not a function. (In 'AbortSignal.timeout((t=this.props.timeout)!==null&&t!==void 0?t:FO)', 'AbortSignal.timeout' is undefined)

image

### PR DESCRIPTION
**Pull request by DasLixou**
Fixes #2609

### CODE REVIEW

**Comment by userquin** [comment]
you must push also pnpm lock file

**Comment by userquin** [comment]
> Ughh.. I just edited on web so I wouldn't have to pull everything... is there a simpler way to just do it on the fly?

Maybe using Review PR button  (will open SB editor in the browser, iirc) and running `pnpm install` from the temrinal.

**Comment by userquin** [comment]
This should fix the error in the linked issue, but may fail when adding attachments (checking the logic):

imagen

**Comment by DasLixou** [comment]
hek, I made a Github search and the ONLY place where `AbortSignal.timeout` was found was in tests/setup.ts - where is that one located?

**Comment by userquin** [comment]
masto: check last entry https://github.com/search?q=repo%3Aneet%2Fmasto.js%20abortsignal.timeout&type=code

**Comment by DasLixou** [comment]
that sucks..
so can we somehow maybe put the tests/setup.ts function implementation in the elk when its not defined?

**Comment by userquin** [comment]
it is not easy, we need a polyfill (I asked Ryo)

**Comment by DasLixou** [comment]
So can this be merged?

**Comment by userquin** [comment]
can you check if the PR preview is working on Safari 15? I cannot test it, @shuuji3 can you test this 🙏 ? Check also Ryo response in discord, masto channel

**Comment by DasLixou** [comment]
Uploading a picture also works (I think it is intended that I'm logged in and it's a test environment, right?)

**Review by userquin — APPROVED** [review]

**Review by patak-dev — APPROVED** [review]

**Pull request merged**
