### PR TITLE
feat(i18n): Adding catalan and valencian locale

### PR DESCRIPTION
**Pull request by carlesbarreda**
I followed the instructions for adding new language in CONTRIBUTING, I hope I did well.

More info for developers about catalan locale can be found on [LocalePlanet](https://www.localeplanet.com/icu/iso639.html#ca)

### CODE REVIEW

**Comment by userquin** [comment]
@carlesbarreda there is a PR here, maybe you can review it: it also includes Valenciano 
https://github.com/elk-zone/elk/pull/1577

About the error, read `CI errors` in contributing guide, `Semantic Pull Requests`.

**Comment by carlesbarreda** [comment]
@userquin I reviewed the PR [#1577](https://github.com/elk-zone/elk/pull/1577) and isn't full translated (mix english and catalan). I translated the last pull using the I18N ally plugin, about 448 strings, and do quick reviewed.
I think the simple way is that I cancel my PR for add the valencian variant and make a new PR.
To speed the process I wrote a script to extract the locale keys haven't translated in .ts file inside t function. I think can rewrite to extract the translated strings and put in the valencian variant file.

**Comment by carlesbarreda** [comment]
@userquin I don't now the way to merge my PR with the PR [#1577](https://github.com/elk-zone/elk/pull/1577) of @rbnval, for this I downloaded manually and extract the valencians strings to incomporate to my PR.
Isn't fairly but I don't now other way to do quick. I can revert this commit if needed.
Also I can share the script if any one need extract strings like in this case.

**Comment by carlesbarreda** [comment]
I can't found the correct valencian language code for browsers can autodetect, but is possible to switch manually in settings.

When select catalan or valencian, in the [preview deploy](https://deploy-preview-1634--elk-zone.netlify.app/), can't traslate toots, if switch to spanish then appear the translate link.

Maybe I miss do something to activate translation in the new locales.

**Pull request closed without merging**
