### PR TITLE
feat: add bold and italic buttons to editor

### PR DESCRIPTION
**Pull request by victordelva**
imagen
imagen

### CODE REVIEW

**Comment by patak-dev** [comment]
This looks good on big screens, but I'm afraid we are already out of space for mobile. @userquin also was working on some advanced features that would require space. And we got a request to hide the code block button. I think we should already have these two new ones and the code block behind a new format button that opens a toolbar on hover maybe?

**Comment by victordelva** [comment]
@patak-dev 
I'll try to work on that

**Comment by victordelva** [comment]
I used a dropdown. this is how it looks on smaller screens. 
What do you think @patak-dev ?

imagen

**Review by boehs — APPROVED** [review]

**Comment by patak-dev** [comment]
It looks like there is a glitch in mobile, the keyboard collapses when the new button is pressed. Maybe is normal but we coupd check if that could be avoided

**Comment by boehs** [comment]
I think a simple e.preventDefault fixes

**Comment by boehs** [comment]
closes #1469

**Pull request merged**
