### PR TITLE
fix: disable auto collapse of the first mentioned account in reply content issue: #2464

### PR DESCRIPTION
**Pull request by HawtinZeng**

### CODE REVIEW

**Comment by HawtinZeng** [comment]
@patak-dev hi, patak, I have saw that your wrote the code related this issue, can u help me to review my code?

**Comment by HawtinZeng** [comment]
#2464 2464

**Comment by patak-dev** [comment]
Not showing the mentions cleans up quite a bit of noise when reading a thread. Let's try to keep the feature. I think we could make it a bit more strict and take into account the text. We could define for example that if the text starts with `,` then we should show the mention.

**Comment by HawtinZeng** [comment]
> Not showing the mentions cleans up quite a bit of noise when reading a thread. Let's try to keep the feature. I think we could make it a bit more strict and take into account the text. We could define for example that if the text starts with `,` then we should show the mention.

That sounds good, i will commit my changes soon.

**Pull request closed without merging**
