### PR TITLE
feat(pwa): add install PWA widget

### PR DESCRIPTION
**Pull request by userquin**
This PR also changes dark icon color, too dark on update prompt.

install-light

install-dark

supersedes #1304

### CODE REVIEW

**Comment by ushuz** [comment]
The install prompt won't go away if I don't install PWA
image

**Comment by userquin** [comment]
@ushuz what browser?

**Comment by ushuz** [comment]
@userquin MS Edge 108 on macOS

**Comment by userquin** [comment]
@ushuz is  there no another more complicated combination to test ;) (just joking)? PWA in macOS and iOS is a pain...

**Comment by msfjarvis** [comment]
@userquin I can also reproduce on Chrome 109.0.5414.119 on Linux. Here's what I did

1. Load up https://main.elk.zone and observe the prompt on the bottom right
2. Press dismiss button
3. Click on the elk logo at top left to reload the page
4. Observe the prompt re-appears

**Comment by userquin** [comment]
@ushuz @msfjarvis can you test it on main.elk.zone? Install widget will not appear if cancelled from widget.

**Comment by ushuz** [comment]
@userquin It's good for me now, looks like #1459 is related

**Pull request merged**
