### PR TITLE
chore(i18n): `en` as source language

### PR DESCRIPTION
**Pull request by edimitchel**
As we have now variants enable, en-US is no more the source of language as it's a variant itself.

So, I suggest to switch too EN ~~and force the [BCP47](https://en.wikipedia.org/wiki/IETF_language_tag) language system~~

### CODE REVIEW

**Comment by userquin** [comment]
I don't use VSCode so I cannot check it: maybe Anthony can help on this.

**Comment by Shinigami92** [comment]
According to this line

https://github.com/lokalise/i18n-ally/blob/435df209ec85bd43181a24635f268dce9d591c90/src/core/Config.ts#L79

it is already the default 🤔 
is it?

**Comment by edimitchel** [comment]
I though the same so actually, we could remove all the config as `en` seems to be the default language source?

**Review by Glaydus — APPROVED** [review]
This is how it should be.
I have it set since changing en_US to en.

**Pull request merged**
