### PR TITLE
chore: update nuxt to 3.11.2

### PR DESCRIPTION
**Pull request by userquin**

### CODE REVIEW

**Comment by danielroe** [comment]
We need to update the lock file too

**Comment by userquin** [comment]
upps, not changed on my local, weird

**Comment by userquin** [comment]
We need to cleanup some dev dependencies:

imagen

**Comment by userquin** [comment]
@danielroe a lot of hmr messages in dev server first time pages load, and it seems a slow on page navigation. 

There are no Vue router warnings in the console :tada:

**Comment by userquin** [comment]
HMR messages:

imagen

**Comment by userquin** [comment]
Emojis cannot be loaded on dev server, I need to check waht's happening and check them also in PR preview.

**Comment by userquin** [comment]
Emojis cannot be loaded on dev server: PR preview working.

**Comment by userquin** [comment]
it seems a problem with unshifting public folders...

**Comment by userquin** [comment]
When requesting an emoji `/emojis/twemoji/1f60d.svg` (clap iirc), adding this middleware to dev server in emoji-mart-translation module:

```ts
       configureServer(server) {
          server.middlewares.use((req, res, next) => {
            const url = req.url
            if (url?.startsWith('/emojis/twemoji/') || url?.startsWith('/avatars/')) {
              console.log(url)
              return next((err) => {
                err && console.error(url, err)
              })
            }
            next()
          })
        },
```

imagen

**Comment by userquin** [comment]
imagen

**Comment by userquin** [comment]
@danielroe The problem seems to be here: https://github.com/nuxt/nuxt/blob/3c90aaf8e21955cf0644df2e0b09e3e33441e8e2/packages/vite/src/client.ts#L182-L184

Shouldn't check if it is on any public folder?

**Comment by userquin** [comment]
How about avatars? I guess it is some nuxt/nitro internal change (3.10 or 3.11), any image in public subfolders not working.

If you check the pwa module (config.ts module) there are a few middlewares added in dev to serve properly sw and web manifest files (using  middlewares stack): I need to check it on my local using `dev:mocked:pwa` script (maybe aldo broken). 

I have done some tests patching nuxt client vite event handler removing the `__skip_vite` hack, ofc it didn't work since vitw cannot resolve the public folder, nuxt vite removes the middleware and vite receives the raw folder without the public dir in the path.

**Comment by userquin** [comment]
It seems we cannot use nuxt aliases like `~/public/xxxx` in `nitro.publicAssets` (not being resolved)

**Review by shuuji3 — APPROVED** [review]
OK, now all emojis and icons look recovered!

Screenshot from 2024-04-05 22-17-02

Screenshot from 2024-04-05 22-17-29

**Pull request merged**
