### PR TITLE
feat: image pinch to zoom

### LINKED ISSUE #1595: Make images in preview zoomable via pinch zoom
On mobile/pwa it is sometimes hard to read content in an image
It should be possible to zoom the image via pinch zoom
The content in background should not be affected by that

### PR DESCRIPTION
**Pull request by JohnyTheCarrot**
fix #1595

We should discuss the UX of this code before I mark it as ready for review, I'd reckon.

### CODE REVIEW

**Review by danielroe — COMMENTED** [review]
This is great - thank you! I wonder about disabling rotation - I think it might feel more stable if it was just scaling that we applied?

**Comment by Shinigami92** [comment]
Yes! that's it, but pls disable rotation

**Comment by peterbud** [comment]
FYI: a PR with similar approach #1367 has been closed recently due to @vueuse/gesture is "not enough battle tested"

**Comment by Shinigami92** [comment]
> FYI: a PR with similar approach #1367 has been closed recently due to @vueuse/gesture is "not enough battle tested"

I don't know, but maybe it's just better implemented now :shrug: 
I tested on my iOS and even in the current state it's a BIG improvement
just the rotation should also be disabled and we should merge this ASAP

**Comment by patak-dev** [comment]
@wheatjs was working on an implementation using another lib IIUC. @wheatjs, maybe you could check how this PR works and we could move forward with it if it works ok enough? And later on, we can improve on it if there is something better to put on the table.

**Comment by wheatjs** [comment]
> @wheatjs was working on an implementation using another lib IIUC. @wheatjs, maybe you could check how this PR works and we could move forward with it if it works ok enough? And later on, we can improve on it if there is something better to put on the table.

I was just talking to @userquin about this and agreed that it should be merged. I think we should disable the rotation first but after that I think it is good enough for now. It will be easier to iterate on this kind of thing ones was have the basic functionality implemented. So after rotation is removed, LGTM

**Comment by JohnyTheCarrot** [comment]
Are we certain this is good enough? There *is* a lack of navigating around a zoomed in image (I.e. focussing on a detail in an image in say the top left), but I am uncertain how we would tackle such a thing.

**Comment by userquin** [comment]
LGTM (if rotation removed), is there any chance to include also swap on desktop via mouse?

**Comment by JohnyTheCarrot** [comment]
Rotation has been removed with my last commit, but what do you mean by swap on desktop?

**Comment by userquin** [comment]
how about zooming with double tap/click (back to initial)?

**Comment by userquin** [comment]
> Rotation has been removed with my last commit, but what do you mean by swap on desktop?

try this on desktop with mouse click https://swiperjs.com/

**Comment by JohnyTheCarrot** [comment]
> > Rotation has been removed with my last commit, but what do you mean by swap on desktop?
> 
> try this on desktop with mouse click https://swiperjs.com/

Do you mean to suggest to use the library behind this as well, or just that the behavior should be like that?

**Comment by wheatjs** [comment]
> Are we certain this is good enough? There _is_ a lack of navigating around a zoomed in image (I.e. focussing on a detail in an image in say the top left), but I am uncertain how we would tackle such a thing in a non frustrating way while somehow figuring out whether the user intended to slide to another image or wanted to move the image view around.

I think right now just getting a basic implementation is what is most important. The app is still in alpha and it is a good time to iterate on these types of features. Also this will hit canary before hitting the main branch, so I think it is okay

**Comment by userquin** [comment]
> Do you mean to suggest to use the library behind this as well, or just that the behavior should be like that?

I'm asking you if we can have mouse click + drag in this PR, the link was to show you an example, this library is the alternative we're checking (`@wheat` and me)

**Review by Shinigami92 — APPROVED** [review]
I just made a blackbox QA and did not check the code / implementation
IMO this is a HUGE improvement :heart:

**Review by userquin — APPROVED** [review]

**Review by patak-dev — APPROVED** [review]
Lets merge and iterate. Thanks @JohnyTheCarrot for pushing this forward 🧡

**Comment by JohnyTheCarrot** [comment]
No problem, glad to help!

**Comment by ushuz** [comment]
Thanks for taking on the problem.

However, this change is behaving weirdly on my desktop (Edge 110 on macOS). After pinch to zoom in and out, images could get upside down, and after that, any pinch action only enlarges the image. Here's a screen recording:

https://user-images.githubusercontent.com/1430856/218328649-0e6ddd30-0a4f-47bd-8a1f-1a4768caaa52.mp4

FYI, does anyone know this library? It's performing amazingly on my Mac, iOS Safari and Android Chrome, not sure about other devices.
https://photoswipe.com/vue-image-gallery/
https://vue-hatnqg.stackblitz.io/

**Pull request merged**
