### PR TITLE
chore: downgrade dependencies to avoid 500 error on `/oauth/callback`

### LINKED ISSUE #3072: Cannot re-authenticate main.elk.zone to Mastodon
A few days ago (26 November), I found that my main.elk.zone Chrome PMA on my Android 15 phone was no longer authorized. Trying to sign in took me to the sign-in page on my instance, where I authorized elk and was redirected back. I tested from directly within chrome and saw the same problem. I got a 500 from main.elk.zone, and the new oauth application was never used. Every time I try the auth flow it creates a new application, and each time I get the 500 from main.elk.zone. I've tried this intermittently until moments before filing this isue.

However, I can successfully log in on elk.zone, so the bug appears to be in main but not yet on stable.

This isn't obviously (to me) the same as #2279

You should find 500s in your logs from 70.229.193.23 for some of these attempts in the past hour.

### PR DESCRIPTION
**Pull request by shuuji3**
fix #3072

I bisect the past Netlify previews and it seems that the 500 error starts after merging #3046. Downgrading nuxt might fix the 500 error on `/oauth/callback` after log-in.

This is only a temporary workaround and I haven't found the root cause of 500 error.

### CODE REVIEW

**Comment by shuuji3** [comment]
Unfortunately, this doesn't fix the issue yet.

Screenshot of page showing "500 This page is temporarily unavailable."

**Comment by shuuji3** [comment]
Another attempt: revert the dependencies to the point (https://github.com/elk-zone/elk/commit/738bc88be2974ad1f79d5fccf2c72824479f01f3) which is the previous commit of https://github.com/elk-zone/elk/pull/3046.

**Comment by shuuji3** [comment]
OK, the 500 error has disappeared now. Some of those updates should be causing the error.

**Comment by shuuji3** [comment]
The above commits with passed CI (✅) had no issue including [chore: update nuxt-component-meta and unstorage in resolutions (90aa666)](https://github.com/elk-zone/elk/pull/3075/commits/90aa66623baf601c1a17d92d57307e4575f6397f) but [chore: update nuxt and @nuxt/schema (b3c961e)](https://github.com/elk-zone/elk/pull/3075/commits/b3c961ee53886ab3f0ba73807d49a40c458911fa) introduced the 500 error again. So there's some issue between the previous nuxt v3.13.2 and v3.14.1592.

**Comment by shuuji3** [comment]
- ❌ [chore: downgrade nuxt from 3.14.1592 to 3.14.159 (ec6e257)](https://github.com/elk-zone/elk/pull/3075/commits/ec6e2574a4fdbdcb2262fe49b0ee36d20a61d88a)
- ❌ [chore: downgrade nuxt from 3.14.159 to 3.14.0 (84ccf66)](https://github.com/elk-zone/elk/pull/3075/commits/84ccf6651acf0a20e05202e81d5747a394b7280c)
- ❌ [chore: downgrade nuxt from 3.14.0 to 3.13.2 (69cc79b)](https://github.com/elk-zone/elk/pull/3075/commits/69cc79b3b81c9cdb84054ad75dc106b296771868)
- ❌ [chore: downgrade nuxt from 3.14.0 to 3.13.2 (32e1908)](https://github.com/elk-zone/elk/pull/3075/commits/32e190852e8fb913be2bbe057e6de7a2ac4a244f)

**Comment by shuuji3** [comment]
I think we can merge this with the previous version of nuxt (v3.13.2) until we can figure out the root cause so that users can sign in on main.elk.zone again.

This might be related to `~~/shared/` folder @userquin pointed out on Nimbus:
https://discord.com/channels/1309441428061163551/1309844382693855232/1309846031726415902
but I'm not sure how exactly that's causing this issue as I cannot see it on local dev server.

**Comment by userquin** [comment]
What's the server error?

**Comment by shuuji3** [comment]
I can see only 500 error on Netlify preview. We need Netlify's server log to check the actually error.

**Comment by shuuji3** [comment]
I'd like to merge this since it also occurs on other endpoints and blocks the other PR previews (e.g. #3033).

Examples:
- status link:
  - https://deploy-preview-3033--elk-zone.netlify.app/universeodon.com/@shuuji3@fedibird.com/113389571144372566
- direct link to the local timeline
  - https://deploy-preview-3033--elk-zone.netlify.app/universeodon.com/public/local
  - though it works when clicking the local timeline button on the navigation
- direct link to the profile page
  - https://deploy-preview-3033--elk-zone.netlify.app/universeodon.com/@elkdev
  - similarly clicking the profile icon on Elk app still works

We can investigate the root cause when we upgrade back to nuxt>=3.14.0 again in a separate PR.

**Review by patak-dev — APPROVED** [review]

**Pull request merged**
