### PR TITLE
feat: more list support

### PR DESCRIPTION
**Pull request by boehs**
#372 

- [x] lists (#1474)
- [x] view accounts in list
- [x] add accounts to list
  - [x] from account
  - [ ] ~~from list page~~ (not this pr)
- [x] remove accounts from list
  - [x] from account
  - [x] from list page
- [ ] change list name
- [ ] create list
- [ ] delete list

known bugs:

- [x] listid not reactive
- [x] bad styling for account "add to list". Possibly bad accessibility as well.

image
image
image

leaving current unchecked features for future prs

### CODE REVIEW

**Comment by boehs** [comment]
@patak-dev review time ❤️

**Comment by patak-dev** [comment]
Nice! 

I think the tabs are great for now, and also the icon to remove from the list.

Do you need to follow a user to be able to have it in a list? I see the button only appears when you follow someone. I imagined lists were also a way to see posts from certain people without following them 🤔 

About the dropdown when pressing the list button on the profile, lets remove the colors and add a checked icon when the user is in that list. I think the current red/green may confuse users. Later on, maybe we should show all the lists the user is part of first, and then the rest as a separate list below, and animate the transition.

**Comment by boehs** [comment]
> Do you need to follow a user to be able to have it in a list? I see the button only appears when you follow someone.

As much as it pains me, I believe so. Every client I've looked at only allows it when following, and the [API Docs](https://docs.joinmastodon.org/methods/lists/#404-not-found-3) are grim.

> lets remove the colors and add a checked icon when the user is in that list.

Sounds good. Unfortunately, remix icons doesn't have a "playlist remove" icon, only the add icon. Other possibilities:

- Normal +/- icons
- User+/User- icons (like on the list accounts page)

Neither are very good, though I'm much more inclined to the second. Curious to know your thoughts or other ideas.

**Comment by patak-dev** [comment]
I think the second option could work until we find something better

**Comment by boehs** [comment]
@patak-dev fixed :)

**Comment by boehs** [comment]
actually don't merge yet, I found a better icon

**Comment by boehs** [comment]
alright, should be good now

**Comment by patak-dev** [comment]
Awesome! Lets merge it to get the functionality. Maybe we could later have the lists the user is in as primary color. Or maybe only show the lists the user is part of, and then a add to list button.

**Pull request merged**
